module.exports = {
  purge: ["./src/**/*.html", "./src/**/*.js"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        green: "#00A149",
        primaryColor: "#FFC222",
        textColor: "#1E1D23",
        primaryColorHover: "#EEAC00",
        overlay: "rgba(0, 0, 0, 0.7)",
        black50: "rgba(0, 0, 0, 0.5)",
        white10: "rgba(255, 255, 255, 0.1)",
        black10: "rgba(0, 0, 0, 0.1)",
        white50: "rgba(255, 255, 255, 0.5)",
        formBg: "#F6F6F6",
        bannerColor: "#242424",
        contentBanner: "#F7F2E2",
        primaryColorOpacity: "#FFF9E8",
        bannerOrange: "#DB731E",
        bannerYellow: "#FFC900",
        footerBg: "#181818",
        pageHeaderBg: "#F8F5F0",
        green10: "#EBF7EE",
        greenBorder: "#BEE5C8",
      },
      outline: {
        primaryColor: ["2px solid #FFC222", "2px"],
      },
      zIndex: {
        0: 0,
        1: 1,
        2: 2,
        75: 75,
        60: 60,
        100: 100,
        999: 999,
        1000: 1000,
        2000: 2000,
      },
      fill: (theme) => ({
        primary: theme("colors.primaryColor"),
        white: theme("colors.white"),
      }),
      fontSize: {
        "7xl": "70px",
        15: "15px",
        40: "40px",
        13: "13px",
        10: "10px",
        11: "11px",
      },
      minWidth: {
        60: "60px",
      },
      keyframes: {
        opacity: {
          from: { opacity: 0 },

          to: { opacity: 1 },
        },
      },
      spacing: {
        13: "13px",
        "1px": "1px",
        72: "72px",
        "5px": "5px",
        "2px": "2px",
        "3px": "3px",
        120: "120px",
        "101%": "101%",
        300: "300px",
        350: "350px",
        70: "70px",
        69: "69px",
        "1/8": "12.5%",
        "8%": "8%",
        500: "500px",
        768: "768px",
        650: "650px",
        530: "530px",
        "3/7": "43%",
        "4/12": "33%",
        "8/12": "67%",
        "4/7": "57%",
        "80px": "80px",
        "130%": "130%",
        "91%": "91%",
        "98%": "98%",
        "96%": "96%",
        "screen-2/3": "67vw",
        "screen-90": "90vh",
        "screen-98": "98vw",
      },
      boxShadow: {
        header: "0 0 30px 0 rgba(0, 0, 0, .1)",
      },
      transitionProperty: {
        height: "height",
      },
      maxHeight: {
        250: "250px",
        400: "400px",
      },
      maxWidth: {
        300: "300px",
      },
      borderRadius: {
        4: "4px",
        20: "20px",
      },
      height: {
        "6/10": "60%",
        "4/10": "40%",
      },
      lineHeight: {
        12: "68px",
        11: "3.2rem",
      },
      scale: {
        25: ".25",
        30: ".30",
        35: ".35",
        40: ".40",
        115: "1.15",
      },
      fontFamily: {
        "Norican-Font": ["'Norican'", "cursive"],
      },
    },
    backgroundImage: {
      "banner-footer": "url(assets/img/content/h1_bg.jpg)",
      "page-header": "url(assets/img/banner/breadcrumb1.jpg)",
      "explore-bg": "url(assets/img/banner/image4-h4.jpg)",
      "banner-right": "url(assets/img/banner/bg1-h4.png)",
      "banner-about-slide": "url(assets/img/about/bg.jpg)",
      "banner-about-l": "url(assets/img/about/banner-l.jpg)",
      "product-img":
        "url(https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/5-1.png",
    },
  },
  variants: {
    extend: {
      borderWidth: ["first"],
      fontWeight: ["first"],
      fontSize: ["first"],
      fill: ["hover", "group-hover", "focus"],
      display: ["group-hover"],
      color: ["group-hover", "group-child-hover"],
      colors: ["first"],
      scale: ["group-hover"],
      visibility: ["group-hover"],
      translate: ["active", "group-hover"],
      transitionProperty: ["group-hover", "hover"],
      width: ["group-hover"],
      height: ["group-hover"],
      opacity: ["group-hover"],
    },
  },
  plugins: [require("@tailwindcss/line-clamp")],
}
